name: Build & Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build site
      uses: jakejarvis/hugo-build-action@master
    - name: Deploy to GitHub
      uses: Mogeko/git-push@master
      with:
        GITHUB_EMAIL: zhengjunyi@live.com
        GITHUB_USERNAME: Mogeko
        GIT_COMMIT: Update Blog By GITHUB Actions With Build '${GITHUB_RUN_ID}'
        GIT_REPO: github.com/Mogeko/mogeko.github.io
        GIT_BRANCH: master
        WORK_DIR: "./public"


