name: Build & Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build
      uses: jakejarvis/hugo-build-action@master
    - name: Deploy
      uses: x-actions/git-push@v1
      env:
        PUBLISH_REPO: https://${{ secrets.GITHUB_TOKEN }}@github.com/Mogeko/mogeko.github.io
        GITHUB_EMAIL: "zhengjunyi@live.com"
        GITHUB_USERNAME: "Mogeko"
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public

