name: Build & Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build site
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    - name: Deploy to GitHub
      uses: Mogeko/git-push@master
      with:
        GH_EMAIL: zhengjunyi@live.com
        GH_USERNAME: Mogeko
        GH_REPO: github.com/Mogeko/mogeko.github.io
        GH_BRANCH: master
        GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        WORK_DIR: "./public"


