name: Build & Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build
      uses: jakejarvis/hugo-build-action@master
    - name: Deploy
      uses: "fnkr/github-action-git-bash@v1"
      secrets: "GITHUB_TOKEN"
      args: cd ./public && git init && git add . && git commit -m \"Update Blog By GitHub Actions With Build $GITHUB_RUN_ID\" && git push --force --quiet \"https://$GITHUB_TOKEN@$GH_REF\" master:master
      env:
        GH_REF: github.com/Mogeko/mogeko.github.io

