name: Build & Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build site
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    - name: Deploy to GitHub
      run: |
        git config --global user.name 'Mogeko'
        git config --global user.email 'zhengjunyi@live.com'
        cd public && git init
        for try in $(seq 10); do
          git commit -m "Build By GitHub Actions on $(date "+%Y-%m-%d %T")"
          if git push -f "https://${{ secrets.DEPLOY_TOKEN }}@github.com/Mogeko/mogeko.github.io"; then
            exit 0
          else
            sleep $(shuf -i 3-10 -n 1)
          fi
        done
        exit 1
