name: Build & Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build
      uses: jakejarvis/hugo-build-action@master
    - name: Deploy
      uses: Mogeko/git-push@master
      with:
        GITHUB_EMAIL: zhengjunyi@live.com
        GITHUB_USERNAME: Mogeko
        PUBLISH_REPO: github.com/Mogeko/mogeko.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: "./public"


