name: Build & Deploy
on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build
      uses: jakejarvis/hugo-build-action@master
    - name: Deploy
      run: |
        cd ./public
        git init
        
      env:
        DEPOLY_TOKEN: ${{ secrets.DEPOLY_TOKEN }}
        GH_REF: github.com/Mogeko/mogeko.github.io
        USER_NAME: Mogeko
        USER_EMAIL: zhengjunyi@live.com

